project_name: htmltomd

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  main: ./cmd/htmltomd/main.go
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

brews:
  - tap:
      owner: david-mk-lawrence
      name: homebrew-html-to-md
      branch: main

    name: htmltomd

    url_template: "https://github.com/david-mk-lawrence/html-to-md/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    homepage: "https://github.com/david-mk-lawrence/html-to-md"

    folder: Formula

    description: "Convert HTML files to markdown"

    licence: "MIT"

gomod:
  proxy: true

signs:
  artifacts: all

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

  format_overrides:
      - goos: windows
        format: zip

  files:
    - LICENCE
    - README.md

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
